### ISSUE TITLE
Kotlin 2.1.0 failure

### ISSUE THREAD

**Issue by hantsy** [jeremymailen/kotlinter-gradle#414]
I tried to update Kotlin to 2.1.0 but encountered a build error. 

```bash
'void org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments.setExtraWarnings(boolean)'
```

It could be an issue kotlinter called the old kotlin compiler 1.9 APIs, https://kotlinlang.slack.com/archives/C0KLZSCHF/p1729256644747559?thread_ts=1729151089.194689&cid=C0KLZSCHF

Thank @dawiddc for posting the debug info, please vote https://github.com/pinterest/ktlint/issues/2882

**Comment by jeremymailen** [comment]
What version of kotlinter are you using? 
You will need to upgrade to 4.5.0 to get support for kotlin 2+.

**Comment by hantsy** [comment]
Already updated to `kotlinter = "4.5.0"` in the *libs.versions.toml* file.

**Comment by rmarquis** [comment]
More information about this issue available here: https://youtrack.jetbrains.com/issue/KT-70543/Gradle-create-migration-guide-for-those-who-are-using-Kotlin-compiler-classes-indirectly-available-in-buildscripts

There's indeed some required fixes in kotlinter to make it work with 2.1.0.

**Comment by hantsy** [comment]
When I commented out the Kotlinter config in *build.gradle.kts*, the build was successful.

**Comment by dawiddc** [comment]
Our error after update from Kotlin 2.0.21 to 2.1.0 (kotlinter 4.5.0):
```kotlin
> Task :lintKotlinIntegration FAILED
lint worker execution error
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/gradle/internal/config/CompilerConfigurationKey
	at org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar$Companion.<clinit>(ComponentRegistrar.kt:33)
	at org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.<clinit>(ComponentRegistrar.kt)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli_base(KotlinCoreEnvironment.kt:753)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:194)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.configureProjectEnvironment(KotlinCoreEnvironment.kt:652)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:468)
	at com.pinterest.ktlint.rule.engine.internal.KotlinPsiFileFactoryKt.initPsiFileFactory(KotlinPsiFileFactory.kt:58)
	at com.pinterest.ktlint.rule.engine.internal.KotlinPsiFileFactoryProvider.getKotlinPsiFileFactory(KotlinPsiFileFactory.kt:32)
	at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:212)
	at com.pinterest.ktlint.rule.engine.internal.CodeFormatter.format(CodeFormatter.kt:51)
	at com.pinterest.ktlint.rule.engine.internal.CodeFormatter.format(CodeFormatter.kt:28)
	at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.lint(KtLintRuleEngine.kt:91)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.execute(LintWorkerAction.kt:49)
```

**Comment by paul-dingemans** [comment]
Problem is indeed caused by Ktlint using the Kotlin `2.0.21` embedded compiler. In `2.1` compiler some keywords have been removed. This results in conflicts with ktlint.

**Comment by jeremymailen** [comment]
Ok, I'll keep an eye on the issue and coordinate resolution. Let me know if there's anything I can help with.
The only other ways I can think of to resolve would be running the plugin in a separate classloader or vendoring the dependencies which would have some tradeoffs.

**Comment by hantsy** [comment]
@jeremymailen Please open an eye on this change, https://kotlinlang.org/docs/whatsnew21.html#compiler-symbols-hidden-from-the-kotlin-gradle-plugin-api, I think this is related to writing Gradle plugin. I also got a warning when building our project with Kotlin 2.1.0

**Comment by paul-dingemans** [comment]
> Problem is indeed caused by Ktlint using the Kotlin `2.0.21` embedded compiler. In `2.1` compiler some keywords have been removed. This results in conflicts with ktlint.

It would be interesting to know whether the problem is solved when you run against 1.4.1-kotlin-dev-SNAPSHOT (for example see https://oss.sonatype.org/content/repositories/snapshots/com/pinterest/ktlint/ktlint-rule-engine/1.4.2-kotlin-dev-SNAPSHOT/) as this was already based on Kotlin 2.1.0-RC2 (https://github.com/pinterest/ktlint/blob/master/gradle/libs.versions.toml#L7).

**Comment by paul-dingemans** [comment]
I have just build ktlint `1.4.2-SNAPSHOT` based on Kotlin `2.1.0` (official release). See https://pinterest.github.io/ktlint/latest/install/snapshot-build/. Please let me know whether the problem is solved with this version.

**Comment by jeremymailen** [comment]
Made the update but I still get a compile error [here](https://github.com/jeremymailen/kotlinter-gradle/actions/runs/12115591125/job/33774251546?pr=415#step:5:160) trying to build the plugin from this [PR](https://github.com/jeremymailen/kotlinter-gradle/pull/415).

**Comment by jeremymailen** [comment]
Oh nevermind, after removing the kotlinter self check, things now build.
@paul-dingemans if you would be so kind as to release 1.4.2 officially I can push a release on my end to resolve.
It's true that we should move to gradle worker classloader isoltion when we can.

**Comment by paul-dingemans** [comment]
I need to solve a few other bugs related to Kotlin 2.1. Will do my best to release this week.

**Comment by jeremymailen** [comment]
Status update. Fixing this will require classloader isolation. I have a [PR out](https://github.com/jeremymailen/kotlinter-gradle/pull/420) which I will test further on some substantial projects. And an additional PR will be needed to maintain support for custom rules. In the end there will be a 5.0.0 release and it will be a substantial change, but hopefully for the better.

**Comment by rock3r** [comment]
Hi! I ran into this in https://github.com/JetBrains/Jewel — I asked folks in JetBrains for help, and they could repro, see [KT-73761](https://youtrack.jetbrains.com/issue/KT-73761/Upgrading-to-Kotlin-2.1.0-fails-with-Could-not-serialize-value-of-type-GradleKotlinCompilerWorkArguments).

The root cause is kotlinter putting kotlin-compiler-embeddable on the buildscript classpath, which causes it to fail when using Kotlin 2.1.0 as the 1.9.24 version kotlinter uses is binary incompatible.

In the meantime, the fix for us was to explicitly put the right version of the compiler in the buildSrc classpath: https://github.com/JetBrains/jewel/commit/8191612ec5e2295ab37a453378641b7e4cf74780

Just thought this could be helpful, even tho the issue seems to be worked on already.

**Comment by hantsy** [comment]
@rock3r I have tried to add it explicitly to build script classpath like.

```kts
buildscript{
    dependencies{
        classpath(xxx)
    }
}
```

But it did not work.

**Comment by jeremymailen** [comment]
Should now be fixed in [5.0.0](https://github.com/jeremymailen/kotlinter-gradle/releases/tag/5.0.0).
Please give it a try.

**Comment by a-glapinski** [comment]
I can confirm that [5.0.0](https://github.com/jeremymailen/kotlinter-gradle/releases/tag/5.0.0) version fixed the problem. Thanks!
